// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-KMZoAhurnXALwwft7bhBguQAgusalM',
    appId: '1:88320362348:web:d2cd6cfd38a475acbed549',
    messagingSenderId: '88320362348',
    projectId: 'awasumina',
    authDomain: 'awasumina.firebaseapp.com',
    storageBucket: 'awasumina.appspot.com',
    measurementId: 'G-FD2NB1D9FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz5YWeRQSXP_4DDTPQ-YkVS8SjFT0o0Qw',
    appId: '1:88320362348:android:e813c85baa648017bed549',
    messagingSenderId: '88320362348',
    projectId: 'awasumina',
    storageBucket: 'awasumina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwfafUNv-oWq3lCYbGgGtgLqxo1JWCecc',
    appId: '1:88320362348:ios:1de16da4bf8eaaa1bed549',
    messagingSenderId: '88320362348',
    projectId: 'awasumina',
    storageBucket: 'awasumina.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
